### PR TITLE
Upgrades Ruby to 3.2.2., 3.1.4, 3.0.6, and 2.7.8 releases

### PR DESCRIPTION
**Pull request by san983**
New Ruby versions were just released

- https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-2-2-released/
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-1-4-released/
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-0-6-released/
- https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/

### CODE REVIEW

**Comment by san983** [comment]
Hi @FooBarWidget, could you please take a look at this? Thanks!

**Comment by FooBarWidget** [comment]
Looking into it now.

**Comment by FooBarWidget** [comment]
The CI is failing on some disk full error. I'll need to find a way to fix this.

**Comment by manuelvanrijn** [comment]
> The CI is failing on some disk full error. I'll need to find a way to fix this. 

@FooBarWidget seen this before. Maybe this can help? https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930

**Comment by FooBarWidget** [comment]
Thanks for the hint, I got it working using that plus a few other tricks (aa2d618).

**Pull request merged**
