### PR TITLE
Upgrade Ruby to 3.3.5

### PR DESCRIPTION
**Pull request by rus-max**
https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/

### CODE REVIEW

**Comment by maxerkin** [comment]
Hi @FooBarWidget, could you please merge this? Thanks!

**Comment by FooBarWidget** [comment]
Testing in CI now.

**Comment by maxerkin** [comment]
CI is passed
@FooBarWidget

**Comment by FooBarWidget** [comment]
Being published now. Thank you.

**Comment by rus-max** [comment]
All jobs were canceled on publishing

**Comment by FooBarWidget** [comment]
There was an error by I retried and now it's finished.

**Pull request merged**
