### PR TITLE
Upgrade Ruby to 3.2.6, 3.3.6

### PR DESCRIPTION
**Pull request by rus-max**
https://www.ruby-lang.org/en/news/2024/10/30/ruby-3-2-6-released/
https://www.ruby-lang.org/en/news/2024/11/05/ruby-3-3-6-released/

### CODE REVIEW

**Comment by rus-max** [comment]
Hi @FooBarWidget, could you please merge this? Thanks!

**Comment by maxerkin** [comment]
I pushed commit with fixes

Sorry, @FooBarWidget

**Comment by rus-max** [comment]
I pushed commit with fixes

Sorry, @FooBarWidget

**Comment by FooBarWidget** [comment]
Retriggering CI.

**Comment by FooBarWidget** [comment]
Looks good. Thanks!

**Comment by maxerkin** [comment]
One of the jobs was failed

@FooBarWidget

**Comment by rus-max** [comment]
@FooBarWidget, could you retry please?

**Pull request merged**
