### PR TITLE
Upgrades Ruby to 3.1.3, 3.0.5, and 2.7.7 releases

### PR DESCRIPTION
**Pull request by san983**
New Ruby versions were just released:

https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-1-3-released/
https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/
https://www.ruby-lang.org/en/news/2022/11/24/ruby-2-7-7-released/

### CODE REVIEW

**Comment by san983** [comment]
Oops, sorry. Just noticed https://github.com/fullstaq-ruby/server-edition/pull/111. We can close this one in favour of #111

**Comment by FooBarWidget** [comment]
Thanks @san983 . #111 needs to be rebased so yours is newer. I'll try yours.

**Comment by FooBarWidget** [comment]
Ruby 3.1.3 and 3.0.5 don't compile on CentOS 7:

~~~
compiling dmyext.c
In file included from vm_core.h:83:0,
                 from iseq.h:14,
                 from mini_builtin.c:3,
                 from miniinit.c:51:
thread_pthread.h:108:43: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'struct'
     RUBY_EXTERN RB_THREAD_LOCAL_SPECIFIER struct rb_execution_context_struct *ruby_current_ec;
                                           ^
In file included from iseq.h:14:0,
                 from mini_builtin.c:3,
                 from miniinit.c:51:
vm_core.h: In function 'rb_current_execution_context':
vm_core.h:1870:34: error: 'ruby_current_ec' undeclared (first use in this function)
     rb_execution_context_t *ec = ruby_current_ec;
                                  ^
vm_core.h:1870:34: note: each undeclared identifier is reported only once for each function it appears in
~~~

Looks like the compiler in CentOS 7 is too old.

You should add some exclusions in config.yml. Exclude 3.0 and 3.1 from centos-7.

**Comment by san983** [comment]
> Ruby 3.1.3 and 3.0.5 don't compile on CentOS 7:
> 
> ```
> compiling dmyext.c
> In file included from vm_core.h:83:0,
>                  from iseq.h:14,
>                  from mini_builtin.c:3,
>                  from miniinit.c:51:
> thread_pthread.h:108:43: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'struct'
>      RUBY_EXTERN RB_THREAD_LOCAL_SPECIFIER struct rb_execution_context_struct *ruby_current_ec;
>                                            ^
> In file included from iseq.h:14:0,
>                  from mini_builtin.c:3,
>                  from miniinit.c:51:
> vm_core.h: In function 'rb_current_execution_context':
> vm_core.h:1870:34: error: 'ruby_current_ec' undeclared (first use in this function)
>      rb_execution_context_t *ec = ruby_current_ec;
>                                   ^
> vm_core.h:1870:34: note: each undeclared identifier is reported only once for each function it appears in
> ```
> 
> Looks like the compiler in CentOS 7 is too old.
> 
> You should add some exclusions in config.yml. Exclude 3.0 and 3.1 from centos-7.

Thanks @FooBarWidget, I noticed the same. Just pushed [03294ca](https://github.com/fullstaq-ruby/server-edition/pull/112/commits/03294ca6f14072198eec4ac9c7cf682e44f31598)

**Comment by FooBarWidget** [comment]
It's merged. Thanks!

**Pull request merged**
