### PR TITLE
Build Ruby 3.1.2, 3.0.4, and 2.7.6

### PR DESCRIPTION
**Pull request by Envek**
See:
 - https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/
 - https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
 - https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/

What I did here:
 1. Bumped patch versions and package revisions in [`config.yml`](https://github.com/fullstaq-ruby/server-edition/pull/94/files#diff-5a7db8dbadaef1b1b5a8738ba70b5ffac82b8e243732154165911284e08aad4b)
 2. Let pre-commit hook to do everything else

### CODE REVIEW

**Comment by san983** [comment]
Cool! thanks for creating the PR :)

**Comment by clemensg** [comment]
Hi @FooBarWidget , would be great to have this merged due to the two CVEs.

**Comment by FooBarWidget** [comment]
Yes on it. Sorry had a busy weekend.

**Comment by FooBarWidget** [comment]
Release done. Thanks @Envek

**Pull request merged**
