### PR TITLE
Upgrade Ruby to 3.2.5

### PR DESCRIPTION
**Pull request by rus-max**
https://www.ruby-lang.org/en/news/2024/07/26/ruby-3-2-5-released/

### CODE REVIEW

**Comment by rus-max** [comment]
Hi @FooBarWidget! 
Сould you please take a look at this?
Thanks!

**Comment by FooBarWidget** [comment]
Hi, I'm in the middle of an infrastructure migration so the deployment pipeline doesn't work yet. I hope to finish it within a couple of days.

**Comment by FooBarWidget** [comment]
The migration is now complete. Could you merge/rebase your pull request against the latest main?

**Comment by maxerkin** [comment]
Completed

@FooBarWidget

**Comment by rus-max** [comment]
Completed

@FooBarWidget

**Comment by FooBarWidget** [comment]
Thanks! It's being deployed now.

**Pull request merged**
