### PR TITLE
Adds Ruby v3.3.0

### PR DESCRIPTION
**Pull request by san983**
Closes https://github.com/fullstaq-ruby/server-edition/issues/131

### CODE REVIEW

**Comment by san983** [comment]
@FooBarWidget I'm not adding [Prism parser](https://github.com/ruby/prism) option yet, as despite it is depicted as `Prism is production ready and actively maintained, you can use it in place of Ripper` in the Ruby 3.3.0 announcement, it actually raises [a warning while using it](https://github.com/ruby/ruby/blob/e5a4f757bdf5dc3d8c329ddd268432f9ecc7bff6/ruby.c#L1412-L1417)

WDYT?

**Comment by FooBarWidget** [comment]
> @FooBarWidget I'm not adding [Prism parser](https://github.com/ruby/prism) option yet, as despite it is depicted as `Prism is production ready and actively maintained, you can use it in place of Ripper` in the Ruby 3.3.0 announcement, it actually raises [a warning while using it](https://github.com/ruby/ruby/blob/e5a4f757bdf5dc3d8c329ddd268432f9ecc7bff6/ruby.c#L1412-L1417)
> 
> WDYT?

Fine with me. Let's revisit that when someone complains, or at the next Ruby version.

**Comment by FooBarWidget** [comment]
The Ruby 3.2 patch doesn't work on Ruby 3.3. I'll update it.

**Comment by FooBarWidget** [comment]
Looks like Ruby 3.3 uses malloc_trim by default. That obsoletes our malloc_trim variant and patch.

**Comment by FooBarWidget** [comment]
It's released now. Thanks again @san983!

**Comment by san983** [comment]
> It's released now. Thanks again @san983!

Thanks you actually @FooBarWidget :)

**Pull request closed without merging**
